=== USEPA-clone/e-manifest/Services-Information/Schema/bill-search-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for the response by the bill search  service",
  "$ref": "#/definitions/BillSearchResponse",
  "definitions": {
    "BillSearchResponse": {
      "type": "object",
      "properties": {
        "totalNumberOfBills": {
          "description": "Total Number Of Bills  for provided search criteria",
          "type": "number"
        },
        "totalNumberOfPages": {
          "description": "Total Number Of Pages for provided search criteria",
          "type": "number"
        },
        "currentPageNumber": {
          "description": "Current Page Number for provided search criteria ",
          "type": "number"
        },
        "searchedParameters": {
          "description": "valid  parameters used in search",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Parameter"
          }
        },
        "warnings": {
          "description": "validation problems  encountered  in search",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Warning"
          }
        },
        "bills": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Bill"
          }
        }
      },
      "additionalProperties": false
    },
    "Parameter": {
      "type": "object",
      "properties": {
        "field ": {
          "type": "string"
        },
        "value ": {
          "type": "string"
        }
      }
    },
    "Warning": {
      "type": "object",
      "properties": {
        "message  ": {
          "type": "string"
        },
        "field ": {
          "type": "string"
        },
        "value ": {
          "type": "string"
        }
      }
    },
    "Bill": {
      "type": "object",
      "properties": {
        "billingAccount": {
          "description": "Contains billing account (EPA site id).",
          "type": "string"
        },
        "billId": {
          "description": "Contains bill id",
          "type": "number"
        },
        "billStatus": {
          "description": " Contains bill status.",
          "type": "string",
          "enum": [
            "Unpaid",
            "InProgress",
            "ReadyForPayment",
            "Paid",
            "SentToCollections",
            "Credit",
            "ZeroBalance"
          ]
        },
        "paymentType": {
          "description": " Contains bill payment type ",
          "type": "string",
          "enum": [
            "Credit",
            "Ach"
          ]
        },
        "totalAmount": {
          "description": "Contains bill total amount. ",
          "type": "number"
        },
        "currentAmount": {
          "description": "Contains bill current amount. ",
          "type": "number"
        },
        "previousAmount": {
          "description": "Contains previous months total current amounts. ",
          "type": "number"
        },
        "previousInterestAmount": {
          "description": "Contains previous months total interest amounts. ",
          "type": "number"
        },
        "previousFlatFeeAmount": {
            "description": "Contains previous months total flat fee amounts. ",
          "type": "number"     
        },
        "previousPenaltyAmount": {
          "description": "Contains previous months total penalty amounts. ",
          "type": "number"
        },
        "previousLateFeeAmount": {
          "description": "Contains previous months total Late Fee amounts. ",
          "type": "number"
        },
        "dueDate": {
          "description": "Contains due date. ",
          "type": "string",
          "format": "date"
        },
        "paidBy": {
          "description": "Contains the bill payee user id",
          "type": "string"
        },
        "createdDate": {
          "description": "Contains the creation date of the bill",
          "type": "string",
          "format": "date-time"
        },
        "updatedDate": {
          "description": "Contains the update date of the bill.",
          "type": "string",
          "format": "date-time"
        },
        "lateFees": {
          "description": "contains list of late fees",
          "type": "array",
          "items": {
            "$ref": "#/definitions/LateFee"
          }
        },
        "revisions": {
          "description": "contains list of revisions",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Revision"
          }
        },
        "recalculationsInfo": {
          "description": "contains list of Recalculations",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RecalculationInfo"
          }
        },
        "totalAmountChanged ": {
          "description": "if true the totalAmount has been changed from the original calculated amount at the beginning of the month",
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "LateFee": {
      "type": "object",
      "properties": {
        "interestAmount": {
          "description": "Contains calculated interest amount. ",
          "type": "number"
        },
        "penaltyAmount": {
          "description": "Contains calculated penalty amount. ",
          "type": "number"
        },
        "lateFeeAmount": {
          "description": "Contains calculated late fee amount.",
          "type": "number"
        },
        "flatFeeAmount": {
          "description": "Contains calculated flat fee amount.",
          "type": "number"
        },
        "status": {
          "description": " Contains status. Industry cannot see lateFees records where status = Inactive ",
          "type": "string",
          "enum": [
            "Active",
            "Inactive"
          ]
        },
        "lateFeeBillId": {
          "description": "foreign key to the Bill which Late Fee is calculated for",
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "Revision": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Contains either Bill Current or Bill Late fee or Total adjusted absolute amount. ",
          "type": "number"
        },
        "billId": {
          "description": "Contains bill id",
          "type": "number"
        },
        "amountType": {
          "description": "Specifies what amount (Current or late fee or Total) was adjusted",
          "type": "string",
          "enum": [
            "Previous",
            "Current",
            "LateFee",
            "LateFeeInterest",
            "LateFeePenalty",
            "LateFeeFlatFee",
            "Total"
          ]
        },
        "adjustmentType": {
          "description": "Specifies how the amount was adjusted",
          "type": "string",
          "enum": [
            "Increase",
            "Decrease",
            "FullPayment"
          ]
        },
        "publicComments": {
          "description": "adjustment comments",
          "type": "string"
        },
        "createdDate": {
          "description": "Contains the adjustment creation date",
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false
    },
    "RecalculationInfo": {
      "type": "object",
      "properties": {
        "recalculationReason ": {
          "type": "string",
          "enum": [
            "OriginalSiteBill",
            "NewSiteBill"
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== USEPA-clone/e-manifest/Services-Information/Schema/manifest-save-return-examples/bill-search-response-example.json
{
  "totalNumberOfBills": 4,
  "totalNumberOfPages": 1,
  "currentPageNumber": 1,
  "searchedParameters": [
    {
      "field": "startDate",
      "value": "Wed Sep 01 00:00:00 EDT 2021"
    },
    {
      "field": "endDate",
      "value": "Fri Oct 01 00:00:00 EDT 2021"
    },
    {
      "field": "billingAccount",
      "value": "AK8570028649"
    }
  ],
  "bills": [
    {
      "billingAccount": "AK8570028649",
      "billId": 13379972,
      "billStatus": "Unpaid",
      "totalAmount": 69.05,
      "currentAmount": 0,
      "previousAmount": 54,
      "previousInterestAmount": 0.05,
      "previousPenaltyAmount": 0,
      "previousLateFeeAmount": 15.05,
      "dueDate": "2021-08-31",
      "createdDate": "2021-07-01T05:00:08.089+0000",
      "updatedDate": "2021-09-07T16:05:59.274+0000",
      "lateFees": [
        {
          "lateFeeBillId": 13040557,
          "interestAmount": 0.05,
          "penaltyAmount": 0,
          "lateFeeAmount": 15.05,
          "flatFeeAmount": 15,
          "status": "Active"
        }
      ]
    },
    {
      "billingAccount": "AK8570028649",
      "billId": 13040557,
      "billStatus": "Unpaid",
      "totalAmount": 54,
      "currentAmount": 54,
      "previousAmount": 0,
      "previousInterestAmount": 0,
      "previousPenaltyAmount": 0,
      "previousLateFeeAmount": 0,
      "dueDate": "2021-07-31",
      "createdDate": "2021-06-04T20:26:43.401+0000",
      "updatedDate": "2021-09-07T16:05:59.275+0000"
    },
    {
      "billingAccount": "AK8570028649",
      "billId": 13558420,
      "billStatus": "Paid",
      "totalAmount": 84.09,
      "currentAmount": 0,
      "previousAmount": 54,
      "previousInterestAmount": 0.09,
      "previousPenaltyAmount": 0,
      "previousLateFeeAmount": 30.09,
      "dueDate": "2021-09-30",
      "createdDate": "2021-08-01T05:00:03.192+0000",
      "updatedDate": "2021-09-07T16:05:59.276+0000",
      "lateFees": [
        {
          "lateFeeBillId": 13040557,
          "interestAmount": 0.09,
          "penaltyAmount": 0,
          "lateFeeAmount": 30.09,
          "flatFeeAmount": 30,
          "status": "Active"
        }
      ],
      "revisions": [
        {
          "amount": 84.09,
          "amountType": "Total",
          "adjustmentType": "FullPayment",
          "publicComments": "TEST",
          "createdDate": "2021-09-07T16:05:59.256+0000",
          "billId": 13558420
        }
      ]
    },
    {
      "billingAccount": "AK8570028649",
      "billId": 13851255,
      "billStatus": "ZeroBalance",
      "totalAmount": 0,
      "currentAmount": 0,
      "previousAmount": 0,
      "previousInterestAmount": 0,
      "previousPenaltyAmount": 0,
      "previousLateFeeAmount": 0,
      "dueDate": "2021-10-31",
      "createdDate": "2021-09-01T05:00:04.592+0000",
      "updatedDate": "2021-10-01T05:00:04.615+0000"
    }
  ]
}
